### ISSUE TITLE
Problem with dispatcher.list

### ISSUE THREAD

**Issue by suharik71** [florentchauveau/kamailio_exporter#20]
Hi,
I found such a problem. when disptacher.list is flat

```
{
	NRSETS: 1
	RECORDS: {
		SET: {
			ID: 10
			TARGETS: {
				DEST: {
					URI: sip:192.168.63.110:5061
					FLAGS: AP
					PRIORITY: 0
				}
			}
		}
	}
}
```
all ok.
but when it has a more advanced format, exporter cannot get data
```
{
	NRSETS: 1
	RECORDS: {
		SET: {
			ID: 10
			TARGETS: {
				DEST: {
					URI: sip:192.168.63.110:5061
					FLAGS: AP
					PRIORITY: 0
					LATENCY: {
						AVG: 2.446000
						STD: 1.561000
						EST: 2.454000
						MAX: 7
						TIMEOUT: 0
					}
				}
			}
		}
	}
}
```

func ReadPacket return null array

cookie dispatcher.list [13 29 104 216]
records dispatcher.list []
[]
2020/06/02 18:18:11 [error] type error: type 2 not implemented

**Comment by florentchauveau** [comment]
Hello,

Which version of kamailio are you using?

**Comment by suharik71** [comment]
kamcmd> core.version
kamailio 5.2.7 (x86_64/linux)
before was
kamailio 5.2.6 (x86_64/linux)

**Comment by scharrua** [comment]
Same here!
kamcmd> core.version
kamailio 5.1.6

**Comment by florentchauveau** [comment]
Hello,

That's because of the binrpc lib that does not recognize the format being returned. 

I'll work on a patch as soon as possible!

**Comment by florentchauveau** [comment]
Hi,

This is fixed in release https://github.com/florentchauveau/kamailio_exporter/releases/tag/v0.4.2

Type "double" was not implemented in the binrpc package.

Enjoy!
